// <auto-generated />
using System;
using DatabaseApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseApi.Migrations
{
    [DbContext(typeof(DataBaseContextModel))]
    [Migration("20240405220434_FourthMigration")]
    partial class FourthMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DatabaseApi.Models.Nationality", b =>
                {
                    b.Property<int?>("NationalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NationalityName")
                        .HasColumnType("longtext");

                    b.HasKey("NationalityId");

                    b.ToTable("Nationalities");

                    b.HasData(
                        new
                        {
                            NationalityId = 9922111,
                            NationalityName = "Indian"
                        },
                        new
                        {
                            NationalityId = 8822111,
                            NationalityName = "Egyptian"
                        },
                        new
                        {
                            NationalityId = 7722111,
                            NationalityName = "Saudi"
                        });
                });

            modelBuilder.Entity("DatabaseApi.Models.Person", b =>
                {
                    b.Property<int?>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float?>("Age")
                        .HasColumnType("float");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int?>("NationalityId")
                        .HasColumnType("int");

                    b.HasKey("PersonId");

                    b.HasIndex("NationalityId")
                        .IsUnique();

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = 111,
                            Age = 28f,
                            BirthDate = new DateTime(1996, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Naveen",
                            NationalityId = 9922111
                        },
                        new
                        {
                            PersonId = 222,
                            Age = 30f,
                            BirthDate = new DateTime(1994, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Umar",
                            NationalityId = 8822111
                        },
                        new
                        {
                            PersonId = 333,
                            Age = 32f,
                            BirthDate = new DateTime(1992, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Qasem",
                            NationalityId = 7722111
                        });
                });

            modelBuilder.Entity("DatabaseApi.Models.Person", b =>
                {
                    b.HasOne("DatabaseApi.Models.Nationality", "Nationality")
                        .WithOne("Person")
                        .HasForeignKey("DatabaseApi.Models.Person", "NationalityId");

                    b.Navigation("Nationality");
                });

            modelBuilder.Entity("DatabaseApi.Models.Nationality", b =>
                {
                    b.Navigation("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
